name: Update_docs

on:
  schedule:
    - cron:  '5 * * * *'

jobs:
    update:
        runs-on: ubuntu-latest
        
        steps:
        - uses: actions/checkout@v2

        - name: Update
          working-directory: ./src/docs
          shell: bash
          run: bash update_docs.sh
